INSERT INTO tbl_movie (category, movie_title, movie_year,additional_info,oscar_won) VALUES
('Best Picture','Black Swain','2010','Nomination in 5 category','false'),
('Best Picture','Chicago','2002','Nomination in 5 category','true'),
('Best Picture','Avatar','2009','Nomination in 5 category','false'),
('Best Picture','The Curious Case of Benjamin Button','2008','Nomination in 5 category','false'),
('Best Picture','Milk','2008','Nomination in 5 category','false'),
('Best Picture','Juno','2007','Nomination in 5 category','false'),
('Best Picture','Babel','2006','Nomination in 5 category','false'),
('Best Picture','Good Night','2005','Nomination in 5 category','false'),
('Best Picture','Ray','2004','Nomination in 5 category','false'),
('Best Picture','In The Bedroom','2003','Nomination in 5 category','false'),
('Best Picture','Sideways','2002','Nomination in 5 category','false'),
('Best Picture','The Kings Speech','2010','Nomination in 5 category','true'),
('Best Picture','The Hurt Locker','2009','Nomination in 5 category','true'),
('Best Picture','Slumdog Millionaire','2008','Nomination in 5 category','true'),
('Best Picture','No Country for old Man','2007','Nomination in 5 category','true'),
('Best Picture','The Departed','2006','Nomination in 5 category','true'),
('Best Picture','Crash','2005','Nomination in 5 category','true'),
('Best Picture','Million Dollar Baby','2004','Nomination in 5 category','true'),
('Best Picture','The Return of the King','2003','Nomination in 5 category','true'),
('Best Picture','A Beautiful Mind','2001','Nomination in 5 category','true');


INSERT INTO tbl_rating(movie_name, rating, user_name, user_email_id, movie_id) VALUES
('Black Swain',10,'Nadia Malek','nadia.malek@gmail.com',1),
('Black Swain',10,'Maruf Malek','maruf.malek@gmail.com',1),
('Chicago',9.5,'Nadia Malek','nadia.malek@gmail.com',2),
('Chicago',9,'Maruf Malek','maruf.malek@gmail.com',2),
('Avatar',9,'Nadia Malek','nadia.malek@gmail.com',3),
('Avatar',8,'Maruf Malek','maruf.malek@gmail.com',3),
('The Curious Case of Benjamin Button',8,'Nadia Malek','nadia.malek@gmail.com',4),
('The Curious Case of Benjamin Button',8.5,'Maruf Malek','maruf.malek@gmail.com',4),
('Milk',8.5,'Nadia Malek','nadia.malek@gmail.com',5),
('Milk',7,'Maruf Malek','maruf.malek@gmail.com',5),
('Juno',7,'Nadia Malek','nadia.malek@gmail.com',6),
('Juno',7.5,'Maruf Malek','maruf.malek@gmail.com',6),
('Babel',7.5,'Nadia Malek','nadia.malek@gmail.com',7),
('Babel',6,'Maruf Malek','maruf.malek@gmail.com',7),
('Good Night',6,'Nadia Malek','nadia.malek@gmail.com',8),
('Good Night',6.5,'Maruf Malek','maruf.malek@gmail.com',8),
('Ray',6.5,'Nadia Malek','nadia.malek@gmail.com',9),
('Ray',5.5,'Maruf Malek','maruf.malek@gmail.com',9),
('In The Bedroom',5.5,'Nadia Malek','nadia.malek@gmail.com',10),
('In The Bedroom',5,'Maruf Malek','maruf.malek@gmail.com',10),
('Sideways',5,'Nadia Malek','nadia.malek@gmail.com',11),
('Sideways',4.5,'Maruf Malek','maruf.malek@gmail.com',11),
('The Kings Speech',4.5,'Nadia Malek','nadia.malek@gmail.com',12),
('The Kings Speech',4,'Maruf Malek','maruf.malek@gmail.com',12);